# Generated by Django 4.2 on 2024-10-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='elements_photos/%Y/%m/%d')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название элемента')),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField(default=800)),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'No active')], default=1)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID категории')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=251, verbose_name='Название категории')),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField(default=800)),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'No active')], default=1)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.sections')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
    ]
