# Generated by Django 4.2 on 2024-10-02 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elements',
            name='sections',
            field=models.ManyToManyField(blank=True, to='app_catalog.sections'),
        ),
    ]
