# Generated by Django 4.2 on 2024-09-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0008_tree_code_tree_app_catalog_code_d4c480_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
