# Generated by Django 4.2 on 2024-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0014_alter_sections_managers_alter_sections_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField(default=800)),
                ('is_active', models.BooleanField(choices=[(1, 'Active'), (0, 'No active')], default=1)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('section', models.ManyToManyField(to='app_catalog.sections')),
            ],
        ),
    ]
