# Generated by Django 4.2 on 2024-09-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0015_elements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elements',
            old_name='section',
            new_name='sections',
        ),
    ]
