# Generated by Django 4.2 on 2024-09-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0020_remove_elements_sections_sections_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='elements',
        ),
        migrations.AddField(
            model_name='elements',
            name='sections',
            field=models.ManyToManyField(to='app_catalog.sections'),
        ),
    ]
