# Generated by Django 4.2 on 2024-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0021_remove_sections_elements_elements_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='elements',
            field=models.ManyToManyField(related_name='+', to='app_catalog.elements'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='sections',
            field=models.ManyToManyField(related_name='+', to='app_catalog.sections'),
        ),
    ]
