# Generated by Django 4.2 on 2024-09-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0025_table1_table2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
        migrations.DeleteModel(
            name='Table2',
        ),
        migrations.AlterField(
            model_name='elements',
            name='sections',
            field=models.ManyToManyField(blank=True, null=True, to='app_catalog.sections'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID категории'),
        ),
    ]
