# Generated by Django 4.2 on 2024-10-01 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_catalog', '0027_elements_photo_alter_elements_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
