# Generated by Django 4.2 on 2024-09-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0004_alter_tree_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.tree'),
        ),
    ]
