# Generated by Django 4.2 on 2024-09-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0005_alter_tree_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
