# Generated by Django 4.2 on 2024-09-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0007_alter_tree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['code'], name='app_catalog_code_d4c480_idx'),
        ),
    ]
