# Generated by Django 4.2 on 2024-09-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0010_remove_tree_app_catalog_code_d4c480_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
