# Generated by Django 4.2 on 2024-09-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0012_rename_tree_catalog_alter_catalog_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Sections',
        ),
    ]
