# Generated by Django 4.2 on 2024-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0013_rename_catalog_sections'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sections',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='sections',
            name='is_active',
            field=models.BooleanField(choices=[(1, 'Active'), (0, 'No active')], default=1),
        ),
    ]
