# Generated by Django 4.2 on 2024-09-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0016_rename_section_elements_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sections',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
