# Generated by Django 4.2 on 2024-09-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0018_alter_elements_id_alter_sections_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sections',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
