# Generated by Django 4.2 on 2024-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0019_alter_elements_id_alter_sections_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='sections',
        ),
        migrations.AddField(
            model_name='sections',
            name='elements',
            field=models.ManyToManyField(to='app_catalog.elements'),
        ),
    ]
