# Generated by Django 4.2 on 2024-09-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0022_sections_elements_alter_elements_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='elements',
        ),
        migrations.AlterField(
            model_name='elements',
            name='sections',
            field=models.ManyToManyField(to='app_catalog.sections'),
        ),
    ]
