# Generated by Django 4.2 on 2024-09-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0023_remove_sections_elements_alter_elements_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elements',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterField(
            model_name='elements',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название элемента'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
    ]
