# Generated by Django 4.2 on 2024-09-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0024_alter_elements_options_alter_sections_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1f1', models.IntegerField()),
                ('t1f2', models.IntegerField()),
                ('t1f3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t2f1', models.IntegerField()),
                ('t2f2', models.IntegerField()),
                ('t2f3', models.IntegerField()),
            ],
        ),
    ]
