# Generated by Django 4.2 on 2024-10-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0028_elements_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=251, verbose_name='Название категории'),
        ),
    ]
